### ISSUE TITLE
IT: java.lang.IllegalArgumentException: Unhandled error id: no_origin_nor_destination

### ISSUE THREAD

**Issue by f-wart** [schildbach/public-transport-enabler#348] opened 2021-01-04 18:14 UTC
### Query
- NetworkId: `IT`
- From: `Location{ADDRESS, 44.8083760/10.2974330, place=Parma, name=Via Battaglia di Fornovo}`
- Via: `null`
- To: `Location{POI, 44.3751500/9.8788810, name=Pontremoli}`
- Date: `Mon Jan 04 18:38:42 GMT+01:00 2021`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error id: no_origin_nor_destination
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1065)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```

### Additional information
[Please modify this part]

**Comment by ialokim** [comment] 2021-05-21 22:29
Duplicate of #349.

**Comment by schildbach** [comment] 2024-08-30 15:55
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.

**Closed by schildbach** 2024-08-30 15:55 UTC
Labels: navitia
