### ISSUE TITLE
SBB: de.schildbach.pte.exception.UnexpectedRedirectException: http://fahrplan.sbb.ch/bin/query.exe/dn?start=Suchen&REQ0JourneyStopsS0ID=A%3D1%40L%3D8508207&REQ0JourneyStopsZ0ID=A%3D1%40L%3D8507091&REQ0HafasSearchForw=1&REQ0JourneyDate=26.07.21&REQ0JourneyTime=11%3A49&REQ0JourneyProduct_prod_list_1=1111111111&h2g-direct=11&clientType=ANDROID -> http://www.sbb.ch/de/fahrplan.html?start=Suchen&REQ0JourneyStopsS0ID=A%3D1%40L%3D8508207&REQ0JourneyStopsZ0ID=A%3D1%40L%3D8507091&REQ0HafasSearchForw=1&REQ0JourneyDate=26.07.21&REQ0JourneyTime=11%3A49&REQ0JourneyProduct_prod_list_1=1111111111&h2g-direct=11&clientType=ANDROID

### ISSUE THREAD

**Issue by tobiwancanobi** [schildbach/public-transport-enabler#382] opened 2021-07-26 09:55 UTC
### Query
- NetworkId: `SBB`
- From: `Location{STATION, 8508207, 46.9392430/7.7842000, name=Langnau i.E.}`
- Via: `null`
- To: `Location{STATION, 8507091, 46.9300110/7.4189860, name=Liebefeld}`
- Date: `Mon Jul 26 11:49:01 GMT+02:00 2021`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
de.schildbach.pte.exception.UnexpectedRedirectException: http://fahrplan.sbb.ch/bin/query.exe/dn?start=Suchen&REQ0JourneyStopsS0ID=A%3D1%40L%3D8508207&REQ0JourneyStopsZ0ID=A%3D1%40L%3D8507091&REQ0HafasSearchForw=1&REQ0JourneyDate=26.07.21&REQ0JourneyTime=11%3A49&REQ0JourneyProduct_prod_list_1=1111111111&h2g-direct=11&clientType=ANDROID -> http://www.sbb.ch/de/fahrplan.html?start=Suchen&REQ0JourneyStopsS0ID=A%3D1%40L%3D8508207&REQ0JourneyStopsZ0ID=A%3D1%40L%3D8507091&REQ0HafasSearchForw=1&REQ0JourneyDate=26.07.21&REQ0JourneyTime=11%3A49&REQ0JourneyProduct_prod_list_1=1111111111&h2g-direct=11&clientType=ANDROID
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:288)
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:218)
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:214)
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment] 2021-07-30 13:55
Duplicate of #381

**Closed by schildbach** 2021-07-30 13:55 UTC
