### ISSUE TITLE
VorProvider: API 'PARSE' error when querying for trips

### ISSUE THREAD

**Issue by tbart** [schildbach/public-transport-enabler#218] opened 2018-08-12 17:56 UTC
Searching VOR for "Wien Wien-Mitte Landstraße" produces a parsing error.
When choosing a route than goes via this station (which works, just choose "Wien Mitte" and the first minutes will be shown as a walk) and then choosing "from here" on "Wien Wien-Mitte Landstraße" you also see the same error, so it is no input error.
![screenshot_transportr_20180809-181203](https://user-images.githubusercontent.com/9994131/44004826-8b51cc8c-9e69-11e8-8beb-d53c4862ea7d.png)

**Comment by sphh** [comment] 2018-10-08 09:19
It's not just "Wien Wien-Mitte Landstraße", it does happen for other locations, such as street names, as well.

**Comment by schildbach** [comment] 2018-10-08 09:32
The problem can be reproduced by running `de.schildbach.pte.live.VorProviderLiveTest.shortTrip()`. It seems to be caused by the API version change to 1.13 (d5e8c3c422432c5ec98c4a78db827797cffe0abd). When I go back to 1.12 queryTrips() succeeds but then other tests fail.

PARSE error is sent by the API and means that the request is invalid in structure somehow (likely an unknown/deprecated tag).

**Comment by schildbach** [comment] 2018-11-17 21:52
Fixed via 05d1a5826be41d7d70a0e3eb15d80db322b7e983

**Closed by schildbach** 2018-11-17 21:52 UTC
Labels: bug
