### ISSUE TITLE
ONTARIO: NO_TRIPS

### ISSUE THREAD

**Issue by sarahmrrp** [schildbach/public-transport-enabler#356] opened 2021-02-04 01:17 UTC
### Query
- NetworkId: `ONTARIO`
- From: `Location{STATION, stop_area:OON:Navitia:9227, 43.6456520/-79.3792100, place=Old Toronto, name=UNION STATION}`
- Via: `null`
- To: `Location{STATION, stop_area:OON:Navitia:23860, 43.7653640/-79.4909540, place=North York, name=FINCH WEST STATION}`
- Date: `Wed Feb 03 20:16:36 EST 2021`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
No connections could be found :(
```

### Additional information
No departure information for stations and  no directions other than walking

**Comment by ialokim** [comment] 2021-05-21 22:24
Duplicate of #354.

**Comment by schildbach** [comment] 2024-08-30 15:58
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.

**Closed by schildbach** 2024-08-30 15:58 UTC
Labels: navitia
