### ISSUE TITLE
Germany - DING Donau Iller Nahverkehrsgmbh - cannot parse xml

### ISSUE THREAD

**Issue by sXOR** [schildbach/public-transport-enabler#453] opened 2022-02-22 09:33 UTC
Due to an update on the api of ding.eu I found following error, it started about 6 weeks ago, I use the android app öffi, it's also from schildbach and hopefully related to this branch

**Query**
Country: DE Germany
From: Ulm Hauptbahnhof
Via: null
To: everywhere
Date: Wed Feb 22 10:29:37 GMT+01
Departure: true
Products: [HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]
Optimize for: LEAST_DURATION
Walk Speed: NORMAL

**Additional information**
Google Play current version, clean install

**Error**
`de.schildbach.pte.exception.ParserException: cannot parse xml: <?xml version="1.0" encoding="UTF-8"?><itdRequest version="10.5.10.21" language="de" lengthUnit="METER" sessionID="370674437" client="okhttp/3.12.13" clientIP="217.31.82.233" serverID="www.ding.eu" virtDir="ding3" calcTime="2450.924" now="2022-02-22T10:34:50" nowWD="3">  <itdVersionInfo>    <ptKernel>      <appVersion>10.5.10.8 build 26.01.2022 02:13:12</appVersion>      <dataFormat>EFA10_04_00</dataFormat>      <dataBuild>2022-02-22T02:12:51</dataBuild>    </ptKernel>  </itdVersionInfo>  <itdInfoLinkList>    <itdBannerInfoList>      <infoLink>        <paramList>          <param edit="0">            <type>addInfoParam</type>            <name>priority</name>            <value>low</value>          </param>          <param edit="0">            <type>addInfoParam</type>            <name>infoType</name>            <value>bannerInfo</value>          </param>          <param edit="0">            <type>system</type>            <name>providerCode</name>            <value>Allgemeine Meldungen (NVBW)</value>          </param>          <param edit="0">            <type>system</type>            <name>infoID</name>            <value>13408_ICSNVBW</value>          </param>          <param edit="0">            <type>system</type>            <name>seqID</name>            <value>2</value>          </param>          <param edit="0">            <type>system</type>            <name>sourceSystemID</name>            <value>ICSNVBW</value>          </param>          <param edit="0">            <type>outputOption</type>            <name>outputArea1</name>            <value>1</value>          </param>        </paramList>        <infoLinkText>Amtliche Wetterwarnungen für Baden-Württemberg</infoLinkText>        <infoLinkURL>http://ics.efa-bw.de:80/cm/XSLT_CM_SHOWADDINFO_REQUEST?infoID=13408_ICSNVBW&amp;seqID=2</infoLinkURL>        <infoLinkImage/>        <infoText>          <content>&lt;p&gt;Die Wetter-Meldungen werden vom Deutschen Wetterdienst zur Verf&amp;uuml;gung gestellt&lt;/p&gt;</content>          <subtitle>Amtliche Wetterwarnungen für Baden-Württemberg</subtitle>          <subject>Amtliche Wetterwarnungen für Baden-Württemberg</subject>          <additionalText></additionalText>          <image></image>          <outputClientText>            <htmlText></htmlText>            <wmlText></wmlText>            <smsText></smsText>            <speechText></speechText>          </outputClientText>          <additionalLinks>            <additionalLink ID="2">              <linkURL>http://www.wettergefahren.de/warnungen/warnsituation/warnlagebericht/baden_wuerttemberg.html</linkURL>              <linkText>Aktuelle Wetter-Warnmeldungen vom Deutschen Wetterdienst</linkText>              <linkTextShort>Aktuelle Wetter-Warnmeldungen vom Deutschen Wetterdienst</linkTextShort>              <linkTarget>_blank</linkTarget>            </additionalLink>          </additionalLinks>        </infoText>      </infoLink>      <infoLink>        <paramList>          <param edit="0">            <type>addInfoParam</type>            <name>priority</name>            <value>high</value>          </param>          <param edit="0">            <type>system</type>            <name>providerCode</name>            <value>Verkehrsgesellschaft Mecklenburg-Vorpommern mbH (VMV)</value>          </param>          <param edit="0">            <type>addInfoParam</type>            <name>infoType</name>            <value>bannerInfo</value>          </param>          <param edit="0">            <type>addInfoParam</type>            <name>position</name>            <value>5</value>          </param>          <param edit="0">            <type>system</type>            <name>infoID</name>            <value>24230_ICSNVBW</value>          </param>          <param edit="0">            <type>outputOption</type>            <name>outputArea1</name>            <value>1</value>          </param>          <param edit="0">            <type>system</type>            <name>seqID</name>            <value>23</value>          </param>          <param edit="0">            <type>system</type>            <name>sourceSystemID</name>            <value>ICSNVBW</value>          </param>        </paramList>        <infoLinkText>Maskenpflicht in Bus &amp; Bahn (M-V)</infoLinkText>        <infoLinkURL>http://ics.efa-bw.de:80/cm/XSLT_CM_SHOWADDINFO_REQUEST?infoID=24230_ICSNVBW&amp;seqID=23</infoLinkURL>        <infoLinkImage/>        <infoText>          <content>&lt;h5&gt;Sogenannte Alltagsmasken aus Stoff, Schals oder T&amp;uuml;cher sind nicht zul&amp;auml;ssig.&lt;/h5&gt;&lt;h5&gt;Ausgenommen sind Kinder bis zum Schuleintritt und Menschen, die aufgrund einer medizinischen oder psychischen Beeintr&amp;auml;chtigung&lt;br /&gt; oder einer Behinderung keine Mund-Nase-Bedeckung tragen k&amp;ouml;nnen und dies durch&lt;br /&gt; eine &amp;auml;rztliche Bescheinigung nachweisen k&amp;ouml;nnen.&lt;/h5&gt;&lt;h5&gt;Sch&amp;uuml;tzen Sie sich und andere!&lt;br /&gt;&lt;br /&gt;Ihre VMV &amp;ndash; Verkehrsgesellschaft Mecklenburg-Vorpommern mbH&lt;/h5&gt;</content>          <subtitle>Maskenpflicht in Bus &amp; Bahn (M-V)</subtitle>          <subject>Im ÖPNV ist das Tragen einer medizinischer Gesichtsmaske verpflichtend, dazu zählen FFP2- sowie OP-Masken.</subject>          <additionalText></additionalText>          <image></image>          <outputClientText>            <htmlText></htmlText>            <wmlText></wmlText>            <smsText></smsText>            <speechText></speechText>          </outputClientText>        </infoText>      </infoLink>    </itdBannerInfoList>  </itdInfoLinkList>  <itdTripRequest requestID="1">    <itdMessage type="warning" module="BROKER" code="-10015" subType="itp-monomodal">itp</itdMessage>    <itdPrintConfiguration active="-1" printerDirect="0" layout="" outputFormat="pdf" fontSizeNormal="1" shading="1" commuterFaresOutput="0" fareUnitOrientation="left" serverAddress="" serverInfo=""/>    <itdAddress name="" street="" place="" addressExt1="" addressExt2=""/>    <itdOdv type="stop" usage="origin" anyObjFilter="0">      <itdOdvPlace state="identified" method="itp">        <odvPlaceElem omc="8421000" placeID="20" value="8421000:20" span="0" type="remote" mainPlace="1" stateless="placeID:8421000:20">Ulm</odvPlaceElem>        <odvPlaceInput></odvPlaceInput>      </itdOdvPlace>      <itdOdvName state="identified" method="itp">        <odvNameElem selected="0" matchQuality="100000" x="9.9841490" y="48.3993654" mapName="WGS84[DD.ddddd]" stopID="9001008" value="9001008:1" isTransferStop="0" stateless="9001008"><itdMapItemList><itdMapItem text="" type="SM"><itdImage src="din/OP_1008.pdf" size="1542"/></itdMapItem></itdMapItemList>Hauptbahnhof</odvNameElem>        <odvNameInput>9001008</odvNameInput>      </itdOdvName>      <itdOdvAssignedStops select="0">        <itdOdvAssignedStop stopID="9001008" x="9.9841490" y="48.3993654" mapName="WGS84[DD.ddddd]" value="9001008:Hauptbahnhof" place="Ulm" nameWithPlace="Ulm Hauptbahnhof" distanceTime="0" isTransferStop="0" vm="100" gid="de:08421:1008">Hauptbahnhof</itdOdvAssignedStop>        <itdOdvAssignedStop stopID="9001000" x="9.9837249" y="48.3983797" mapName="WGS84[DD.ddddd]" value="9001000:ZOB Ost" place="Ulm" nameWithPlace="Ulm ZOB Ost" distance="91" distanceTime="1" isTransferStop="0" vm="100" gid="de:08421:1000">ZOB Ost</itdOdvAssignedStop>        <itdOdvAssignedStop stopID="9001010" x="9.9867300" y="48.4008361" mapName="WGS84[DD.ddddd]" value="9001010:Theater" place="Ulm" nameWithPlace="Ulm Theater" distance="227" distanceTime="3" isTransferStop="0" vm="100" gid="de:08421:1010">Theater</itdOdvAssignedStop>        <itdOdvAssignedStop stopID="9001348" x="9.9816583" y="48.3969585" mapName="WGS84[DD.ddddd]" value="9001348:ZOB West" place="Ulm" nameWithPlace="Ulm ZOB West" distance="366" distanceTime="5" isTransferStop="0" vm="100" gid="de:08421:1348">ZOB West</itdOdvAssignedStop>        <itdOdvAssignedStop stopID="9001001" x="9.9875242" y="48.3972140" mapName="WGS84[DD.ddddd]" value="9001001:Steinerne Brücke" p
de.schildbach.pte.AbstractEfaProvider.lambda$queryTrips$8(AbstractEfaProvider.java:2105)
de.schildbach.pte.AbstractEfaProvider.lambda$queryTrips$8$AbstractEfaProvider(Unknown Source:0)
de.schildbach.pte.-$$Lambda$AbstractEfaProvider$5eRue_1lU86jlgZKDWwyxAlX2bA.onSuccessful(Unknown Source:6)
Cause: com.android.org.kxml2.io.KXmlParser.require(KXmlParser.java:2067)
de.schildbach.pte.util.XmlPullUtil.exit(XmlPullUtil.java:83)
de.schildbach.pte.AbstractEfaProvider.processItdOdv(AbstractEfaProvider.java:701)`

**Comment by sXOR** [comment] 2022-02-22 09:35
![Screenshot_20220222_103455_de grobox liberario](https://user-images.githubusercontent.com/52215996/155104257-0f56f2ec-1f01-454b-8b36-7e6bdc5781c8.jpg)

**Comment by schildbach** [comment] 2022-02-22 10:06
Please don't post error messages as screenshots. Rather, post the complete error as text.

In any case, I think the issue has already been fixed via 2c147075e434672f94e561b6f96cda726178f936.

**Comment by sXOR** [comment] 2022-02-22 11:10
i updated my initial post, sorry for the inconfience, so we just have to wait till googleplay rolls out the updates?

**Comment by schildbach** [comment] 2022-02-22 13:12
Ok, seeing more of the stack trace this is perhaps another issue.

I was able to reproduce a crash once, and just added this commit to help with debugging: 36bc759742972891d778636383622f02db71eb78

But since then, I could not reproduce the crash any more. Do you? What start/end are you using in your query exactly?

**Comment by sXOR** [comment] 2022-02-22 23:19
i tried my start point from many locations insinde the Ding terretory, end points localy, regional and over regional till berlin - all with the same result.

i'm curious about the fact that theyr own online traffic information system stopped working at the same time where öffi stopped working for me, something about 05.01.2022, they must have changed somethign at this time. im using it every day, obviously after some days, about 07.01.2022 theyr online traffic info system worked again. im not working there but im pretty aware of anything could have happen.. since im something like an it specialist i just hope i can assist with some hints, im undiscribeable happy to se there could be a fix in the future!

**Comment by sXOR** [comment] 2022-02-22 23:35
its working!! <3

**Comment by sXOR** [comment] 2022-02-22 23:35
much love!!

**Closed** 2022-02-22 23:35 UTC

**Comment by ghtux** [comment] 2022-06-29 08:49
Same problem for me. Error:

de.schildbach.pte.exception.ParserException: cannot parse xml: <?xml version="1.0" encoding="UTF-8"?><itdRequest version="10.5.15.2" language="de" lengthUnit="METER" sessionID="1062891562" client="okhttp/3.12.13" clientIP="217.31.82.233" serverID="www.ding.eu" virtDir="ding3" calcTime="925.467" now="2022-06-29T10:45:08" nowWD="4">  <itdVersionInfo>    <ptKernel>      <appVersion>10.5.15.7 build 24.06.2022 04:02:36</appVersion>      <dataFormat>EFA10_04_00</dataFormat>      <dataBuild>2022-06-29T02:32:43</dataBuild>    </ptKernel>  </itdVersionInfo>  <itdInfoLinkList>    <itdBannerInfoList>      <infoLink>        <paramList>          <param edit="0">            <type>addInfoParam</type>            <name>priority</name>            <value>low</value>          </param>          <param edit="0">            <type>addInfoParam</type>            <name>infoType</name>            <value>bannerInfo</value>          </param>          <param edit="0">            <type>system</type>            <name>providerCode</name>            <value>Allgemeine Meldungen (NVBW)</value>          </param>          <param edit="0">            <type>system</type>            <name>infoID</name>            <value>13408_ICSNVBW</value>          </param>          <param edit="0">            <type>outputOption</type>            <name>outputArea1</name>            <value>1</value>          </param>          <param edit="0">            <type>system</type>            <name>seqID</name>            <value>2</value>          </param>          <param edit="0">            <type>system</type>            <name>sourceSystemID</name>            <value>ICSNVBW</value>          </param>        </paramList>        <infoLinkText>Amtliche Wetterwarnungen für Baden-Württemberg</infoLinkText>        <infoLinkURL>http://ics.efa-bw.de:80/cm/XSLT_CM_SHOWADDINFO_REQUEST?infoID=13408_ICSNVBW&amp;seqID=2</infoLinkURL>        <infoLinkImage/>        <infoText>          <content>&lt;p&gt;Die Wetter-Meldungen werden vom Deutschen Wetterdienst zur Verf&amp;uuml;gung gestellt&lt;/p&gt;</content>          <subtitle>Amtliche Wetterwarnungen für Baden-Württemberg</subtitle>          <subject>Amtliche Wetterwarnungen für Baden-Württemberg</subject>          <additionalText></additionalText>          <image></image>          <outputClientText>            <htmlText></htmlText>            <wmlText></wmlText>            <smsText></smsText>            <speechText></speechText>          </outputClientText>          <additionalLinks>            <additionalLink ID="2">              <linkURL>http://www.wettergefahren.de/warnungen/warnsituation/warnlagebericht/baden_wuerttemberg.html</linkURL>              <linkText>Aktuelle Wetter-Warnmeldungen vom Deutschen Wetterdienst</linkText>              <linkTextShort>Aktuelle Wetter-Warnmeldungen vom Deutschen Wetterdienst</linkTextShort>              <linkTarget>_blank</linkTarget>            </additionalLink>          </additionalLinks>        </infoText>      </infoLink>      <infoLink>        <paramList>          <param edit="0">            <type>addInfoParam</type>            <name>priority</name>            <value>normal</value>          </param>          <param edit="0">            <type>system</type>            <name>providerCode</name>            <value>Verkehrsgesellschaft Mecklenburg-Vorpommern mbH (VMV)</value>          </param>          <param edit="0">            <type>addInfoParam</type>            <name>infoType</name>            <value>bannerInfo</value>          </param>          <param edit="0">            <type>system</type>            <name>infoID</name>            <value>27028_ICSNVBW</value>          </param>          <param edit="0">            <type>outputOption</type>            <name>outputArea1</name>            <value>1</value>          </param>          <param edit="0">            <type>system</type>            <name>seqID</name>            <value>2</value>          </param>          <param edit="0">            <type>system</type>            <name>sourceSystemID</name>            <value>ICSNVBW</value>          </param>        </paramList>        <infoLinkText>Maskenpflicht in Bus &amp; Bahn (M-V)</infoLinkText>        <infoLinkURL>http://ics.efa-bw.de:80/cm/XSLT_CM_SHOWADDINFO_REQUEST?infoID=27028_ICSNVBW&amp;seqID=2</infoLinkURL>        <infoLinkImage/>        <infoText>          <content>&lt;p&gt;Im &amp;Ouml;PNV gilt die Maskenpflicht, dazu z&amp;auml;hlen FFP2- sowie OP-Masken.&lt;/p&gt;&lt;p&gt;Sogenannte Alltagsmasken aus Stoff, Schals oder T&amp;uuml;cher sind nicht zul&amp;auml;ssig.&lt;/p&gt;&lt;p&gt;Ausgenommen sind Kinder bis zum Schuleintritt und Menschen, die aufgrund einer medizinischen oder psychischen Beeintr&amp;auml;chtigung oder einer Behinderung keine Mund-Nase-Bedeckung tragen k&amp;ouml;nnen und dies durch eine &amp;auml;rztliche Bescheinigung nachweisen k&amp;ouml;nnen.&lt;/p&gt;&lt;p&gt;Sch&amp;uuml;tzen Sie sich und andere!&lt;br /&gt; &lt;br /&gt; Ihre VMV &amp;ndash; Verkehrsgesellschaft Mecklenburg-Vorpommern mbH&lt;/p&gt;</content>          <subtitle>Maskenpflicht in Bus &amp; Bahn (M-V)</subtitle>          <subject></subject>          <additionalText></additionalText>          <image></image>          <outputClientText>            <htmlText></htmlText>            <wmlText></wmlText>            <smsText></smsText>            <speechText></speechText>          </outputClientText>        </infoText>      </infoLink>      <infoLink>        <paramList>          <param edit="0">            <type>addInfoParam</type>            <name>priority</name>            <value>normal</value>          </param>          <param edit="0">            <type>system</type>            <name>providerCode</name>            <value>Allgemeine Meldungen (NVBW)</value>          </param>          <param edit="0">            <type>addInfoParam</type>            <name>infoType</name>            <value>bannerInfo</value>          </param>          <param edit="0">            <type>system</type>            <name>infoID</name>            <value>27035_ICSNVBW</value>          </param>          <param edit="0">            <type>outputOption</type>            <name>outputArea1</name>            <value>1</value>          </param>          <param edit="0">            <type>system</type>            <name>seqID</name>            <value>1</value>          </param>          <param edit="0">            <type>system</type>            <name>sourceSystemID</name>            <value>ICSNVBW</value>          </param>        </paramList>        <infoLinkText>Vom 1.6. bis 31.8. alle Ziele im Regional- und Nahverkehr deutschlandweit für nur 9 Euro/Monat</infoLinkText>        <infoLinkURL>http://ics.efa-bw.de:80/cm/XSLT_CM_SHOWADDINFO_REQUEST?infoID=27035_ICSNVBW&amp;seqID=1</infoLinkURL>        <infoLinkImage/>        <infoText>          <content>Vom 1. Juni bis 31. August alle Ziele im Regional- und Nahverkehr deutschlandweit f&amp;uuml;r nur 9 Euro/Monat&lt;br /&gt;&lt;br /&gt;Weitere Infos unter &lt;a title="Infos &amp;uuml;ber 9-Euro-Ticket" href="https://www.bwegt.de/9-euro-ticket" target="_blank"&gt;https://www.bwegt.de/9-euro-ticket&lt;/a&gt;</content>          <subtitle>Vom 1.6. bis 31.8. alle Ziele im Regional- und Nahverkehr deutschlandweit für nur 9 Euro/Monat</subtitle>          <subject></subject>          <additionalText></additionalText>          <image></image>          <outputClientText>            <htmlText></htmlText>            <wmlText></wmlText>            <smsText></smsText>            <speechText></speechText>          </outputClientText>        </infoText>      </infoLink>      <infoLink>        <paramList>          <param edit="0">            <type>addInfoParam</type>            <name>priority</name>            <value>normal</value>          </param>          <param edit="0">            <type>system</type>            <name>providerCode</name>            <value>Allgemeine Meldungen (NVBW)</value>          </param>          <param edit="0">            <type>addInfoParam</type>            <name>infoType<
de.schildbach.pte.AbstractEfaProvider.lambda$queryTrips$8(AbstractEfaProvider.java:2105)
de.schildbach.pte.AbstractEfaProvider.lambda$queryTrips$8$AbstractEfaProvider(Unknown Source:0)
de.schildbach.pte.-$$Lambda$AbstractEfaProvider$5eRue_1lU86jlgZKDWwyxAlX2bA.onSuccessful(Unknown Source:6)
Cause: com.android.org.kxml2.io.KXmlParser.require(KXmlParser.java:2067)
de.schildbach.pte.util.XmlPullUtil.exit(XmlPullUtil.java:83)
de.schildbach.pte.AbstractEfaProvider.processItdOdv(AbstractEfaProvider.java:701)
