### ISSUE TITLE
BVG: java.io.IOException: got response: 307 Temporary Redirect: https://bvg-apps.hafas.de/bin/mgate.exe

### ISSUE THREAD

**Issue by besendorf** [schildbach/public-transport-enabler#391] opened 2021-08-23 10:37 UTC
### Query
- NetworkId: `BVG`
- From: `Location{STATION, 900078201, 52.4693890/13.4427210, place=Berlin, name=S+U Neukölln, products=[SUBURBAN_TRAIN, SUBWAY, BUS]}`
- Via: `null`
- To: `Location{STATION, 900120001, 52.5135800/13.4758460, place=Berlin, name=S+U Frankfurter Allee, products=[SUBURBAN_TRAIN, SUBWAY, TRAM, BUS]}`
- Date: `Mon Aug 23 12:36:56 GMT+02:00 2021`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `FAST`

### Error
```
java.io.IOException: got response: 307 Temporary Redirect: https://bvg-apps.hafas.de/bin/mgate.exe
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:293)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:205)
de.schildbach.pte.AbstractHafasClientInterfaceProvider.jsonTripSearch(AbstractHafasClientInterfaceProvider.java:583)
```

### Additional information
Using transportr 2.1.2. happenes since ca 2 weeks

**Comment by derhuerst** [comment] 2021-08-23 10:46
The new endpoint is `https://bvg.hafas.cloud/bin/mgate.exe`.

**Comment by schildbach** [comment] 2021-08-23 11:02
Duplicate of #386

**Closed by schildbach** 2021-08-23 11:02 UTC
