### ISSUE TITLE
Switzerland Zurich ZVV network stopped working

### ISSUE THREAD

**Issue by tomgagdotnet** [schildbach/public-transport-enabler#612] opened 2024-12-14 22:22 UTC
Transportr was working great with the zvv.ch local transport network until a few weeks ago. Now it does not:

![image](https://github.com/user-attachments/assets/094bf6b7-6fde-411c-9b6e-0a64b75cbdec)

Thanks a lot!

**Comment by derhuerst** [comment] 2024-12-15 17:04
This is a duplicate of https://github.com/schildbach/public-transport-enabler/issues/606.

**Comment by schildbach** [comment] 2024-12-15 17:09
Fixed via 81b1122204481bc980b091961244ecdb1a86aec0.

**Closed by schildbach** 2024-12-15 17:09 UTC
