### ISSUE TITLE
Switzerland: SBB Not work

### ISSUE THREAD

**Issue by Mannshoch** [schildbach/public-transport-enabler#381] opened 2021-07-24 18:07 UTC
My first request on https://github.com/grote/Transportr/issues/768#issuecomment-886039671

**Describe the bug**
SBB do not work

May helpfull - SBB API: 
https://data.sbb.ch/api/v2/console
https://data.sbb.ch/api/v1/console

**Comment by sirtoobii** [comment] 2021-07-25 13:59
It seems that SBB has shutdown (or moved) their hafas [endpoint](http://fahrplan.sbb.ch/bin/query.exe). @Mannshoch This API [Journey-Service](https://developer.sbb.ch/apis/journey-service/information) seems to be the right one - however I'm not sure if this project gets an "official approval" as stated on their info page...

**Comment by schildbach** [comment] 2021-07-30 14:00
If someone wants to investigate into this, please feel free to.

There are Hafas endpoints for TPG and BLS which would cover at least parts of Switzerland (Geneva and Berne).

- https://bls.hafas.de/bin/mgate.exe
- https://tpg-webapp.hafas.de/bin/mgate.exe

**Comment by alexander-albers** [comment] 2021-07-30 16:51
There's still the [mgate.exe](http://fahrplan.sbb.ch/bin/mgate.exe) endpoint, but I haven't tried yet whether it is actually useful. What's interesting is that accessing the endpoint through Chrome works without any problems but accessing the site through code results in a `302 moved` response. Same also with `http://fahrplan.sbb.ch/bin/stboard.exe/dn` (which works through Chrome), while `http://fahrplan.sbb.ch/bin/ajax-getstop.exe` always returns just an empty response.
It would be really a shame if they have indeed shutdown the current API if favor of a closed-data solution.

**Comment by sirtoobii** [comment] 2021-07-31 10:13
I've started implementing [https://timetable.search.ch/api/](https://timetable.search.ch/api/help) (#383 ). Their [TOS](https://timetable.search.ch/api/terms) seem to be ok with our use-case.

**Comment by gnu1dea** [comment] 2021-08-01 12:56
Maybe https://opentransportdata.swiss/ could be useful.

**Comment by sirtoobii** [comment] 2021-08-01 13:38
@gnu1dea Thank you for your hint! However, I far as I can tell, they offer no "route-planer" and since this project relies on external route-planing capabilities this data-source is unfortunately not compatible.

**Comment by derhuerst** [comment] 2021-08-23 21:43
> * https://bls.hafas.de/bin/mgate.exe

[`transport-apis` contains the necessary details for accessing this endpoint](https://github.com/public-transport/transport-apis/blob/v1/data/ch/bls-hafas-mgate.json).

> * https://tpg-webapp.hafas.de/bin/mgate.exe

[`transport-apis` contains the necessary details for accessing this endpoint](https://github.com/public-transport/transport-apis/blob/v1/data/ch/tpg-hafas-mgate.json).

**Comment by derhuerst** [comment] 2021-08-23 21:44
> There's still the [mgate.exe](http://fahrplan.sbb.ch/bin/mgate.exe) endpoint, but I haven't tried yet whether it is actually useful. What's interesting is that accessing the endpoint through Chrome works without any problems but accessing the site through code results in a `302 moved` response.

Huh, I always get redirected to `://www.sbb.ch/de/fahrplan.html`, with both `http:` and `https:`, and with both Firefox and `curl`. Can you confirm this?

**Comment by alexander-albers** [comment] 2021-08-24 12:34
@derhuerst 
> Huh, I always get redirected to `://www.sbb.ch/de/fahrplan.html`, with both `http:` and `https:`, and with both Firefox and `curl`. Can you confirm this?

Yeah, sorry, seems like my browser had the site cached or something - I cannot reproduce it anymore either. :/

**Comment by schildbach** [comment] 2021-08-24 14:14
@derhuerst Do you think the SBB endpoint will return?

**Comment by derhuerst** [comment] 2021-08-24 14:43
I really don't know, I don't have any background information.

**Comment by schildbach** [comment] 2021-08-24 15:07
My guess is it will not return anytime soon. They don't have any incentive to. Both their website and their mobile app use their own proprietary API (wrapper?).

**Comment by schildbach** [comment] 2021-08-24 19:25
I removed the SbbProvider via 8f8439744b116ddb458cf2659542b9d4946a7dc9.

**Comment by schildbach** [comment] 2021-08-24 19:29
Progress on https://timetable.search.ch/api/help support is tracked via https://github.com/schildbach/public-transport-enabler/pull/383. If anyone wants to implement the TPG and/or BLS endpoints (see above), feel free to comment here.

I'm closing this, as the availability of the original SBB API is beyond our control.

**Closed by schildbach** 2021-08-24 19:29 UTC

**Comment by tinloaf** [comment] 2023-08-29 22:19
Just a note on this (closed, I know) ticket: I think[1] the API officially recommended by SBB to implement custom journey planners is the OJP API provided by SBB: https://opentransportdata.swiss/de/cookbook/open-journey-planner-ojp/

Fun fact: There's actually an upcoming workshop hosted by SBB to teach people how to use OJP: https://workshoptage.ch/workshops/2023/using-ojp-sdk-to-develop-journey-planning-applications/

[1] I'm not an employee of SBB, so this is not an officially SBB-endorsed statement.

**Comment by sirtoobii** [comment] 2023-08-30 06:24
Hey @tinloaf 
Yes, and this format seems to be an emerging standard so I guess it would make sense to implement it in a generic way (like the `AbstractHafasEndpoint`) - however, it would be again a major undertaking...

And just as a sidenote: There is a working adapter for Switzerland atm #481
