### ISSUE TITLE
SBB: de.schildbach.pte.exception.UnexpectedRedirectException: http://fahrplan.sbb.ch/bin/query.exe/dn?start=Suchen&REQ0JourneyStopsS0ID=A%3D1%40L%3D8501120&REQ0JourneyStopsZ0ID=A%3D1%40L%3D8501008&REQ0HafasSearchForw=1&REQ0JourneyDate=14.08.21&REQ0JourneyTime=10%3A50&REQ0JourneyProduct_prod_list_1=1111111111&h2g-direct=11&clientType=ANDROID -> http://www.sbb.ch/de/fahrplan.html?start=Suchen&REQ0JourneyStopsS0ID=A%3D1%40L%3D8501120&REQ0JourneyStopsZ0ID=A%3D1%40L%3D8501008&REQ0HafasSearchForw=1&REQ0JourneyDate=14.08.21&REQ0JourneyTime=10%3A50&REQ0JourneyProduct_prod_list_1=1111111111&h2g-direct=11&clientType=ANDROID

### ISSUE THREAD

**Issue by wombatch** [schildbach/public-transport-enabler#388] opened 2021-08-14 08:51 UTC
### Query
- NetworkId: `SBB`
- From: `Location{STATION, 8501120, 46.5167950/6.6290950, name=Lausanne}`
- Via: `null`
- To: `Location{STATION, 8501008, 46.2102090/6.1424550, name=Genève}`
- Date: `Sat Aug 14 10:50:21 GMT+02:00 2021`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
de.schildbach.pte.exception.UnexpectedRedirectException: http://fahrplan.sbb.ch/bin/query.exe/dn?start=Suchen&REQ0JourneyStopsS0ID=A%3D1%40L%3D8501120&REQ0JourneyStopsZ0ID=A%3D1%40L%3D8501008&REQ0HafasSearchForw=1&REQ0JourneyDate=14.08.21&REQ0JourneyTime=10%3A50&REQ0JourneyProduct_prod_list_1=1111111111&h2g-direct=11&clientType=ANDROID -> http://www.sbb.ch/de/fahrplan.html?start=Suchen&REQ0JourneyStopsS0ID=A%3D1%40L%3D8501120&REQ0JourneyStopsZ0ID=A%3D1%40L%3D8501008&REQ0HafasSearchForw=1&REQ0JourneyDate=14.08.21&REQ0JourneyTime=10%3A50&REQ0JourneyProduct_prod_list_1=1111111111&h2g-direct=11&clientType=ANDROID
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:288)
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:218)
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:214)
```

### Additional information
[Please modify this part]

**Comment by sirtoobii** [comment] 2021-08-17 19:09
Duplicate of #381

**Closed** 2021-08-19 13:49 UTC
