### ISSUE TITLE
SNCB: java.lang.RuntimeException: CLIENTVERSION 

### ISSUE THREAD

**Issue by draxaris1010** [schildbach/public-transport-enabler#493] opened 2022-11-04 12:37 UTC
### Query
- NetworkId: `SNCB`
- From: `Location{STATION, [PRIVATE], [PRIVATE], place=[PRIVATE], name=[PRIVATE], products=[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, TRAM, BUS]}`
- Via: `null`
- To: `Location{STATION, [PRIVATE], [PRIVATE], name=[PRIVATE], products=[HIGH_SPEED_TRAIN, REGIONAL_TRAIN]}`
- Date: `Fri Nov 04 13:31:04 GMT+01:00 2022`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.RuntimeException: CLIENTVERSION 
de.schildbach.pte.AbstractHafasClientInterfaceProvider.jsonTripSearch(AbstractHafasClientInterfaceProvider.java:590)
de.schildbach.pte.AbstractHafasClientInterfaceProvider.queryTrips(AbstractHafasClientInterfaceProvider.java:214)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
```

### Additional information
The old official app also stopped working, same CLIENTVERSION error.
This is likely due to an api change.

**Comment by adipascu** [comment] 2023-01-24 19:47
This is a duplicate of #493 (there is more information in the other ticket).

**Comment by draxaris1010** [comment] 2023-02-02 08:27
> This is a duplicate of #493 (there is more information in the other ticket).

It's this issue you're referencing

**Closed** 2023-02-09 14:45 UTC
