### ISSUE TITLE
Searches for the Paris area stopped working

### ISSUE THREAD

**Issue by khinsen** [schildbach/public-transport-enabler#269] opened 2019-06-26 09:21 UTC
I have been using this library (via [Transportr](https://transportr.app/) on Android) for a few months with good results and no major problems when travelling in and around Paris. But about a week ago, it stopped working. Every search leads to an error message starting with `BlockedException`, such as in this example:

```
de.schildbach.pte.exception.BlockedException: https://api.navitia.io/v1/journeys?from=stop_area%3AOIF%3ASA%3A8768600&to=stop_area%3AOIF%3ASA%3A59%3A3909052&datetime=20190626T111238&datetime_represents=departure&min_nb_journeys=6&depth=0&walking_speed=1.12
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:300)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:217)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:205)
```

**Comment by schildbach** [comment] 2019-10-11 12:01
ParisProvider works reasonably fine atm. Can you still reproduce the issue?

**Comment by khinsen** [comment] 2019-10-12 15:45
No, but that doesn't mean that it works fine for me. I have tried from time to time since I originally reported the problem. I always got errors on any search I tried, but the error message changed over time. Right now, it says that the starting position cannot be found and that I should select another one (no matter which place I select from the list). The precise text in French is: "Imposible de trouver le lieu « de ». Veuillez en essayer un autre."

**Comment by schildbach** [comment] 2024-08-30 16:01
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.

**Closed by schildbach** 2024-08-30 16:01 UTC
Labels: navitia
