### ISSUE TITLE
SNCB: java.lang.RuntimeException: CLIENTVERSION 

### ISSUE THREAD

**Issue by Grorom** [schildbach/public-transport-enabler#535] opened 2023-05-26 22:46 UTC
### Query
- NetworkId: `SNCB`
- From: `Location{STATION, 8813003, 50.8456490/4.3568020, name=Bruxelles-Central, products=[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBWAY, BUS]}`
- Via: `null`
- To: `Location{STATION, 8814001, 50.8357070/4.3365310, name=Bruxelles-Midi, products=[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBWAY, TRAM, BUS]}`
- Date: `Sat May 27 00:18:13 GMT+02:00 2023`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.RuntimeException: CLIENTVERSION 
de.schildbach.pte.AbstractHafasClientInterfaceProvider.jsonTripSearch(AbstractHafasClientInterfaceProvider.java:590)
de.schildbach.pte.AbstractHafasClientInterfaceProvider.queryTrips(AbstractHafasClientInterfaceProvider.java:214)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
```

### Additional information
[Please modify this part]

**Comment by ialokim** [comment] 2023-10-07 21:27
duplicate of #502, this one can be closed.

**Closed** 2023-10-08 08:37 UTC
